---
abstract: 'Executable for App::OS::Detect::MachineCores'
author:
  - 'Daniel B. <dbr@cpan.org>'
build_requires:
  Carp: 0
  ExtUtils::MakeMaker: 0
  File::Spec::Functions: 0
  List::Util: 0
  Module::Build: 0.3601
  Scalar::Util: 0
  Test::CheckDeps: 0.002
  Test::More: 0.94
  Test::UseAllModules: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300017, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-OS-Detect-MachineCores
provides:
  App::OS::Detect::MachineCores:
    file: lib/App/OS/Detect/MachineCores.pm
    version: 0.020
requires:
  Any::Moose: 0
  FindBin: 0
  MooseX::Getopt: 0
  MooseX::Getopt::Dashes: 0
  MouseX::Getopt: 0
  MouseX::Getopt::Dashes: 0
  MouseX::NativeTraits: 0
  perl: 5.010
  strict: 0
  true: 0
  warnings: 0
version: 0.020
x_authority: cpan:DBR
